name: cyberbullying
dependencies:
  - python=2.7
  - pip
  - pip:
    - matplotlib==2.2.3
    - numpy==1.16.6
    - keras==2.0.6
    - pandas==0.24.2
    - scipy==1.2.3
    - decorator==4.4.2
    - ipywidgets==7.5
    - tweet-preprocessor==0.4.0
    - tensorflow==1.15.0
    - tflearn==0.5.0
    - argparse==1.4.0
    - scikit-learn==0.19.0
    - textblob==0.17.1
    - jupyter[notebook]==1.0.0